import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { LegalModal } from "@/components/legal-modal";
import { StoreProvider } from "@/lib/store/StoreProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "sonner";

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "RECON - This is Recon your AI powered detective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${DMSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider >
          <TooltipProvider>
            {children}
          </TooltipProvider>
          <LegalModal />
          <Toaster position="top-center" richColors />
        </StoreProvider>
      </body>
    </html>
  );
}
